language: java
jdk:
  - oraclejdk8

sudo: required

script: mvn test -PNoUi

addons:
  apt:
    packages:
    - oracle-java8-installer

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "app/target/dev-toolkit-jar-with-dependencies.jar"
    - "app/target/dev-toolkit.exe"
    - "plugin-example/target/plugin-example.jar"
    - "plugin-teamcity-warning/target/plugin-teamcity-warning-jar-with-dependencies.jar"
  skip_cleanup: true
  on:
    tags: true