//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.19 at 08:43:54 PM CEST 
//


package com.cydercode.devtoolkit.configuration.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="preset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ignorable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "preset",
    "ignorable"
})
@XmlRootElement(name = "child-preset")
public class ChildPreset
    implements Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected String preset;
    @XmlElement(defaultValue = "false")
    protected Boolean ignorable = false;

    /**
     * Gets the value of the preset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreset() {
        return preset;
    }

    /**
     * Sets the value of the preset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreset(String value) {
        this.preset = value;
    }

    /**
     * Gets the value of the ignorable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIgnorable() {
        return ignorable;
    }

    /**
     * Sets the value of the ignorable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIgnorable(Boolean value) {
        this.ignorable = value;
    }

    public ChildPreset withPreset(String value) {
        setPreset(value);
        return this;
    }

    public ChildPreset withIgnorable(Boolean value) {
        setIgnorable(value);
        return this;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ChildPreset)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ChildPreset that = ((ChildPreset) object);
        {
            String lhsPreset;
            lhsPreset = this.getPreset();
            String rhsPreset;
            rhsPreset = that.getPreset();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "preset", lhsPreset), LocatorUtils.property(thatLocator, "preset", rhsPreset), lhsPreset, rhsPreset)) {
                return false;
            }
        }
        {
            Boolean lhsIgnorable;
            lhsIgnorable = this.isIgnorable();
            Boolean rhsIgnorable;
            rhsIgnorable = that.isIgnorable();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ignorable", lhsIgnorable), LocatorUtils.property(thatLocator, "ignorable", rhsIgnorable), lhsIgnorable, rhsIgnorable)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String thePreset;
            thePreset = this.getPreset();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "preset", thePreset), currentHashCode, thePreset);
        }
        {
            Boolean theIgnorable;
            theIgnorable = this.isIgnorable();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ignorable", theIgnorable), currentHashCode, theIgnorable);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String thePreset;
            thePreset = this.getPreset();
            strategy.appendField(locator, this, "preset", buffer, thePreset);
        }
        {
            Boolean theIgnorable;
            theIgnorable = this.isIgnorable();
            strategy.appendField(locator, this, "ignorable", buffer, theIgnorable);
        }
        return buffer;
    }

}
