//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.19 at 08:46:38 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://cydercode.com/dev-toolkit/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cydercode.devtoolkit.configuration.model;
